"""update user portrait.

Revision ID: 0ee6e078841a
Revises: 927c3f4b50f7
Create Date: 2020-04-01 10:55:50.219060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee6e078841a'
down_revision = '927c3f4b50f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_l', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('avatar_m', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('avatar_s', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_s')
    op.drop_column('user', 'avatar_m')
    op.drop_column('user', 'avatar_l')
    # ### end Alembic commands ###
