"""addition relational The Follow methods and models.

Revision ID: 367a164e680d
Revises: db8ef9c65f28
Create Date: 2020-04-06 20:59:58.016441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367a164e680d'
down_revision = 'db8ef9c65f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.add_column('comments', sa.Column('flag', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'flag')
    op.drop_table('follow')
    # ### end Alembic commands ###
