"""Role one to many...

Revision ID: 5c6df2cb512e
Revises: 7d8da010d723
Create Date: 2020-03-29 21:19:42.670232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c6df2cb512e'
down_revision = '7d8da010d723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_permissions')
    op.add_column('permission', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'permission', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permission', type_='foreignkey')
    op.drop_column('permission', 'role_id')
    op.create_table('roles_permissions',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name='roles_permissions_permission_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='roles_permissions_role_id_fkey')
    )
    # ### end Alembic commands ###
