"""addition flag filed into the Post model.

Revision ID: 7ec7581c9509
Revises: 0ee6e078841a
Create Date: 2020-04-02 17:54:07.074109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec7581c9509'
down_revision = '0ee6e078841a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('flag', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'flag')
    # ### end Alembic commands ###
