"""photo model have added two fields that they are different size file name.

Revision ID: 927c3f4b50f7
Revises: f19f8eeb04a6
Create Date: 2020-03-31 16:43:43.574332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927c3f4b50f7'
down_revision = 'f19f8eeb04a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('filename_m', sa.String(length=64), nullable=True))
    op.add_column('photo', sa.Column('filename_s', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'filename_s')
    op.drop_column('photo', 'filename_m')
    # ### end Alembic commands ###
