"""addition website and location fileds into the User model.

Revision ID: d1b5f2249f03
Revises: d0c3520279ee
Create Date: 2020-04-17 11:39:05.332003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b5f2249f03'
down_revision = 'd0c3520279ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'locked')
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
