"""add field that can be commented on to the Photo model.

Revision ID: db8ef9c65f28
Revises: 95ad3f7ad83d
Create Date: 2020-04-05 20:56:27.090733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8ef9c65f28'
down_revision = '95ad3f7ad83d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('can_comment', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'can_comment')
    # ### end Alembic commands ###
