"""empty message

Revision ID: e7734b5099db
Revises: c8057aef95e9
Create Date: 2020-03-15 15:39:12.602338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7734b5099db'
down_revision = 'c8057aef95e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_table', sa.Column('body', sa.String(length=200), nullable=True))
    op.add_column('message_table', sa.Column('name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_table', 'name')
    op.drop_column('message_table', 'body')
    # ### end Alembic commands ###
